apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-clock-service
  labels:
    app: {{ .Release.Name }}-clock-service
    chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  replicas: {{ .Values.replicaCount }}
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-clock-service
        release: {{ .Release.Name }}
    spec:
      dnsPolicy: ClusterFirst
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.clock.image.repository }}:{{ .Values.clock.image.tag }}"
          env:
            - name: NODE_NAME
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
            - name: POD_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
            - name: http_proxy
              value: $(NODE_NAME):4140
          imagePullPolicy: {{ .Values.clock.image.pullPolicy }}
          ports:
            - name: {{ .Chart.Name }}
              containerPort: 8080
          livenessProbe:
            httpGet:
              path: /clock-service/api/clock
              port: 8080
            initialDelaySeconds: 20
            periodSeconds: 3
          readinessProbe:
            httpGet:
              path: /clock-service/api/clock
              port: 8080
            initialDelaySeconds: 20

