apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-k8s-hello
  labels:
    app: {{ .Release.Name }}-k8s-hello
    chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  replicas: {{ .Values.replicaCount }}
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-k8s-hello
        release: {{ .Release.Name }}
    spec:
      dnsPolicy: ClusterFirst
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.hello.image.repository }}:{{ .Values.hello.image.tag }}"
          env:
            - name: NODE_NAME
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
            - name: POD_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
            - name: http_proxy
              value: $(NODE_NAME):4140
          imagePullPolicy: {{ .Values.hello.image.pullPolicy }}
          ports:
            - name: {{ .Chart.Name }}
              containerPort: 8080
          livenessProbe:
            httpGet:
              path: /
              port: 8080
            initialDelaySeconds: 20
            periodSeconds: 3
          readinessProbe:
            httpGet:
              path: /
              port: 8080
            initialDelaySeconds: 20
          resources:
{{ toYaml .Values.resources | indent 12 }}
    {{- if .Values.nodeSelector }}
      nodeSelector:
{{ toYaml .Values.nodeSelector | indent 8 }}
    {{- end }}
