---
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: {{ .Release.Name }}-k8s-hello-hpa
spec:
  scaleTargetRef:
    apiVersion: extensions/v1beta1
    kind: Deployment
    name: {{ .Release.Name }}-k8s-hello
  minReplicas: {{ .Values.hello.replicaCount }}
  maxReplicas: 4
  targetCPUUtilizationPercentage: 80