# Default values for k8s-hello.

hello:
  image:
    repository: 10.21.154.82:30400/k8s-hello
    tag: latest
    pullPolicy: IfNotPresent
  replicaCount: 2
clock:
  image:
      repository: 10.21.154.82:30400/clock-service
      tag: latest
      pullPolicy: IfNotPresent
  replicaCount: 2
service:
  name: k8s-hello
  type: ClusterIP
linkerd:
  service:
    name: linkerd-l5d
    namespace: linkerd
    port: 80
#DEPRECATED
#  externalPort: 8080
#  internalPort: 8080
resources:
  requests:
    cpu: 200m
    memory: 600Mi
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  # limits:
  #  cpu: 100m
  #  memory: 128Mi
  # requests:
  #  cpu: 100m
  #  memory: 128Mi
