# Default values for k8s-hello.
hello:
  image:
    repository: 10.21.154.82:30400/k8s-hello
    tag: latest
    pullPolicy: Always
  replicaCount: 2
  javaOpts: "-Djava.awt.headless=true -Xms40m -Xmx128m -XX:MaxMetaspaceSize=128m -Denvironment=kubernetes -Duser.timezone=America/Sao_Paulo -Duser.country=BR -Duser.language=pt -Duser.region=BR"
clock:
  image:
      repository: 10.21.154.82:30400/clock-service
      tag: latest
      pullPolicy: Always
  replicaCount: 2
  javaOpts: "-Djava.awt.headless=true -Xms40m -Xmx128m -XX:MaxMetaspaceSize=128m -Duser.timezone=America/Sao_Paulo -Duser.country=BR -Duser.language=pt -Duser.region=BR"
service:
  name: k8s-hello
  type: ClusterIP
linkerd:
  service:
    name: linkerd-l5d
    namespace: linkerd
    port: 80
resources:
  requests:
    cpu: 500m
    memory: 512Mi
  limits:
    cpu: 800m
    memory: 600Mi
timezone:
  path: /usr/share/zoneinfo/America/Sao_Paulo
